apiVersion: batch/v1
kind: Job
metadata:
  name: tf-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      runtimeClassName: nvidia
      containers:
      - name: hello
        image: nvidia/cuda:11.0.3-base-ubuntu20.04
        command: ["nvidia-smi"]
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
