apiVersion: batch/v1
kind: Job
metadata:
  name: worker-0
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      runtimeClassName: nvidia
      containers:
      - name: worker-container-0
        image: nvidia/cuda:11.0.3-base-ubuntu20.04
        args:
        - /bin/bash
        - -c
        - apt-get update -y && apt-get install git -y && git clone https://github.com/A-Wanderer/K8s.git && bash K8s/k8s/tf/script/start.sh
        env:
        - name: TF_CONFIG
          value: '"cluster": { "worker": ["localhost:3333"] }, "task": {"type": "worker", "index": 0}'
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
