apiVersion: batch/v1
kind: Job
metadata:
  name: worker-0
spec:
  # 不设置自动清理 ttlSecondsAfterFinished: 100
  backoffLimit: 1  # 设置重试次数为1
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: OnFailure  # 确保在任务失败后不关闭Pod
      containers:
      - name: worker-container-0
        image: tensorflow/tensorflow:latest-gpu
        args:
        - /bin/bash
        - -c
        - apt-get update -y && apt-get install git -y && git clone https://github.com/A-Wanderer/K8s.git && bash K8s/k8s/tf/script/start.sh
        env:
        - name: TF_CONFIG
          value: '{"cluster": { "worker": ["localhost:3333"] }, "task": {"type": "worker", "index": 0} }'
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
