apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  # 结束后存活时间
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        args:
        - /bin/sh
        - -c
        - echo "Hello, Kubernetes CPU!" && sleep 30
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
      restartPolicy: Never